name: "Label PR"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Uploads repository content to the runner
    - uses: actions/labeler@v5
      with:
        configuration-path: '.github/labeler.yml'