name: Server - Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'src/server/**/*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Build solution
        run: dotnet build
        working-directory: ./src/server
        
      - name: Run tests
        run: dotnet test --no-build --no-restore
        working-directory: ./src/server