name: Server - Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    paths:
      - 'src/server/**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache .NET SDK
        uses: actions/cache@v2
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0

      - name: Build and Test
        run: |
          cd src/server
          dotnet restore
          dotnet build
          dotnet test